spring:
  application:
    name: demo
    wiremock:
      url: ${WIREMOCK_URL:http://localhost:8080}
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
  # cache:
  #   type: redis
